num_actions: 29
obs_builder: "mjlab"  # only mjlab is supported for policy inference

kps: [100, 100, 100, 150, 40, 40,
      100, 100, 100, 150, 40, 40,
      150, 150, 150,
      40, 40, 40, 40, 4.0, 4.0, 4.0,
      40, 40, 40, 40, 4.0, 4.0, 4.0]

kds: [2, 2, 2, 4, 2, 2,
      2, 2, 2, 4, 2, 2,
      4, 4, 4,
      5, 5, 5, 5, 0.2, 0.2, 0.2,
      5, 5, 5, 5, 0.2, 0.2, 0.2]

default_angles: [-0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                 -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                 0, 0, 0,
                 0, 0.4, 0, 1.2, 0.0, 0.0, 0.0,
                 0, -0.4, 0, 1.2, 0.0, 0.0, 0.0]

action_scale: 0.5

torque_limits: [100, 100, 100, 150, 40, 40,
                100, 100, 100, 150, 40, 40,
                150, 150, 150,
                40, 40, 40, 40, 4.0, 4.0, 4.0,
                40, 40, 40, 40, 4.0, 4.0, 4.0]

sim_dt: 0.001

xml_path: "GMR/assets/unitree_g1/g1_sim2sim_29dof.xml"
base_body: "pelvis"

ang_vel_scale: 0.25
dof_pos_scale: 1.0
dof_vel_scale: 0.05
ankle_idx: [4, 5, 10, 11]

mujoco_default_qpos: [0, 0, 0.793,
                      1, 0, 0, 0,
                      -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                      -0.2, 0.0, 0.0, 0.4, -0.2, 0.0,
                      0, 0, 0,
                      0, 0.2, 0, 1.2, 0.0, 0.0, 0.0,
                      0, -0.2, 0, 1.2, 0.0, 0.0, 0.0]
