"""Public constants for the tracking training task."""

OFFICIAL_TASK = "Tracking-Flat-G1-NoStateEst"
NO_ROOT_POSE_TASK = "Tracking-Flat-G1-NoRootPose"
DEFAULT_TRAIN_MOTION_FILE = "data/datasets/twist2_full/train.npz"
DEFAULT_EXPERIMENT_NAME = "g1_tracking"
NO_ROOT_POSE_EXPERIMENT_NAME = "g1_tracking_no_root_pose"
HISTORY_CNN_TASK = "Tracking-Flat-G1-HistoryCNN"
HISTORY_CNN_EXPERIMENT_NAME = "g1_tracking_history_cnn"
YAW_ONLY_TASK = "Tracking-Flat-G1-YawOnly"
YAW_ONLY_EXPERIMENT_NAME = "g1_tracking_yaw_only"
